"""Command-line interface for AgentForge."""

from pathlib import Path
from typing import Annotated

import typer

from agentforge.config.loader import ConfigLoadError
from agentforge.core.runner import WorkflowExecutionError, WorkflowRunner
from agentforge.patches import PatchReviewError, PatchReviewService

app = typer.Typer(help="Run composable software-development agent workflows.")
patch_app = typer.Typer(help="Review and apply patch proposals from a previous run.")
app.add_typer(patch_app, name="patch")


@app.callback()
def main() -> None:
    """Run composable software-development agent workflows."""


@app.command()
def run(
    workflow_path: Annotated[
        Path,
        typer.Argument(help="Path to a workflow YAML file."),
    ],
    input_text: Annotated[
        str,
        typer.Option("--input", help="Request for the workflow to process."),
    ],
    project_root: Annotated[
        Path | None,
        typer.Option("--project-root", help="Project directory exposed to read-only tools."),
    ] = None,
    no_project_context: Annotated[
        bool,
        typer.Option("--no-project-context", help="Disable deterministic read-only project tools."),
    ] = False,
) -> None:
    """Run a YAML-defined workflow."""
    if project_root is not None and no_project_context:
        typer.echo(
            "Error: --project-root and --no-project-context cannot be used together.",
            err=True,
        )
        raise typer.Exit(code=1)

    try:
        result = WorkflowRunner().run(
            workflow_path,
            input_text,
            project_root=project_root,
            use_project_context=not no_project_context,
        )
    except (ConfigLoadError, WorkflowExecutionError) as error:
        typer.echo(f"Error: {error}", err=True)
        raise typer.Exit(code=1) from error

    typer.echo(f"Workflow '{result.workflow_name}' completed successfully.")
    typer.echo(f"Run artifacts: {result.run_directory}")


@patch_app.command("list")
def list_patches(
    run_id: Annotated[
        str,
        typer.Argument(help="Run ID under .agentforge/runs."),
    ],
) -> None:
    """List patch proposals generated by a previous run."""
    try:
        proposals = PatchReviewService().list_patches(run_id)
    except PatchReviewError as error:
        _exit_with_error(error)

    if not proposals:
        typer.echo("No patch proposals found.")
        return

    typer.echo("ID\tAgent\tTarget file\tStatus\tTitle")
    for proposal in proposals:
        typer.echo(
            "\t".join(
                [
                    proposal.id,
                    proposal.agent_name,
                    proposal.target_file,
                    proposal.status,
                    proposal.title,
                ]
            )
        )


@patch_app.command("show")
def show_patch(
    run_id: Annotated[
        str,
        typer.Argument(help="Run ID under .agentforge/runs."),
    ],
    patch_id: Annotated[
        str,
        typer.Argument(help="Patch proposal ID to display."),
    ],
) -> None:
    """Print the diff for one patch proposal."""
    try:
        diff_text = PatchReviewService().show_patch(run_id, patch_id)
    except PatchReviewError as error:
        _exit_with_error(error)

    typer.echo(diff_text.rstrip("\n"))


@patch_app.command("apply")
def apply_patch(
    run_id: Annotated[
        str,
        typer.Argument(help="Run ID under .agentforge/runs."),
    ],
    patch_id: Annotated[
        str,
        typer.Argument(help="Patch proposal ID to apply."),
    ],
    project_root: Annotated[
        Path,
        typer.Option(
            "--project-root",
            exists=True,
            file_okay=False,
            dir_okay=True,
            resolve_path=True,
            help="Project root where the selected patch may write.",
        ),
    ],
) -> None:
    """Apply one explicitly selected patch proposal."""
    try:
        target_path = PatchReviewService().apply_patch(run_id, patch_id, project_root)
    except PatchReviewError as error:
        _exit_with_error(error)

    typer.echo(f"Applied patch '{patch_id}' to {target_path}")


def _exit_with_error(error: PatchReviewError) -> None:
    typer.echo(f"Error: {error}", err=True)
    raise typer.Exit(code=1) from error


if __name__ == "__main__":
    app()
