"""Command-line interface for AgentForge."""

from pathlib import Path
from typing import Annotated

import typer

from agentforge.config.loader import ConfigLoadError
from agentforge.core.runner import WorkflowExecutionError, WorkflowRunner
from agentforge.dev import DevPipelineError, DevPipelineRunner, DevRunResult, DevRunSession
from agentforge.patches import PatchReviewError, PatchReviewService
from agentforge.testing import DEFAULT_TEST_TIMEOUT_SECONDS, TestRunError, TestRunner

app = typer.Typer(help="Run composable software-development agent workflows.")
patch_app = typer.Typer(help="Review and apply patch proposals from a previous run.")
test_app = typer.Typer(help="Detect and run project test commands.")
dev_app = typer.Typer(help="Run the human-approved end-to-end development pipeline.")
app.add_typer(patch_app, name="patch")
app.add_typer(test_app, name="test")
app.add_typer(dev_app, name="dev")

DEFAULT_DEV_WORKFLOW_PATH = Path("examples/workflows/basic_feature.yaml")


@app.callback()
def main() -> None:
    """Run composable software-development agent workflows."""


@app.command()
def run(
    workflow_path: Annotated[
        Path,
        typer.Argument(help="Path to a workflow YAML file."),
    ],
    input_text: Annotated[
        str,
        typer.Option("--input", help="Request for the workflow to process."),
    ],
    project_root: Annotated[
        Path | None,
        typer.Option("--project-root", help="Project directory exposed to read-only tools."),
    ] = None,
    no_project_context: Annotated[
        bool,
        typer.Option("--no-project-context", help="Disable deterministic read-only project tools."),
    ] = False,
) -> None:
    """Run a YAML-defined workflow."""
    if project_root is not None and no_project_context:
        typer.echo(
            "Error: --project-root and --no-project-context cannot be used together.",
            err=True,
        )
        raise typer.Exit(code=1)

    try:
        result = WorkflowRunner().run(
            workflow_path,
            input_text,
            project_root=project_root,
            use_project_context=not no_project_context,
        )
    except (ConfigLoadError, WorkflowExecutionError) as error:
        typer.echo(f"Error: {error}", err=True)
        raise typer.Exit(code=1) from error

    typer.echo(f"Workflow '{result.workflow_name}' completed successfully.")
    typer.echo(f"Run artifacts: {result.run_directory}")


@patch_app.command("list")
def list_patches(
    run_id: Annotated[
        str,
        typer.Argument(help="Run ID under .agentforge/runs."),
    ],
) -> None:
    """List patch proposals generated by a previous run."""
    try:
        proposals = PatchReviewService().list_patches(run_id)
    except PatchReviewError as error:
        _exit_with_error(error)

    if not proposals:
        typer.echo("No patch proposals found.")
        return

    typer.echo("ID\tAgent\tTarget file\tStatus\tTitle")
    for proposal in proposals:
        typer.echo(
            "\t".join(
                [
                    proposal.id,
                    proposal.agent_name,
                    proposal.target_file,
                    proposal.status,
                    proposal.title,
                ]
            )
        )


@patch_app.command("show")
def show_patch(
    run_id: Annotated[
        str,
        typer.Argument(help="Run ID under .agentforge/runs."),
    ],
    patch_id: Annotated[
        str,
        typer.Argument(help="Patch proposal ID to display."),
    ],
) -> None:
    """Print the diff for one patch proposal."""
    try:
        diff_text = PatchReviewService().show_patch(run_id, patch_id)
    except PatchReviewError as error:
        _exit_with_error(error)

    typer.echo(diff_text.rstrip("\n"))


@patch_app.command("apply")
def apply_patch(
    run_id: Annotated[
        str,
        typer.Argument(help="Run ID under .agentforge/runs."),
    ],
    patch_id: Annotated[
        str,
        typer.Argument(help="Patch proposal ID to apply."),
    ],
    project_root: Annotated[
        Path,
        typer.Option(
            "--project-root",
            exists=True,
            file_okay=False,
            dir_okay=True,
            resolve_path=True,
            help="Project root where the selected patch may write.",
        ),
    ],
) -> None:
    """Apply one explicitly selected patch proposal."""
    try:
        target_path = PatchReviewService().apply_patch(run_id, patch_id, project_root)
    except PatchReviewError as error:
        _exit_with_error(error)

    typer.echo(f"Applied patch '{patch_id}' to {target_path}")


@test_app.command("detect")
def detect_test_command(
    project_root: Annotated[
        Path,
        typer.Option(
            "--project-root",
            exists=True,
            file_okay=False,
            dir_okay=True,
            resolve_path=True,
            help="Project root to inspect for likely test commands.",
        ),
    ],
) -> None:
    """Show likely test commands without running them."""
    try:
        assessments = TestRunner().detect_candidates(project_root)
    except TestRunError as error:
        typer.echo(f"Error: {error}", err=True)
        raise typer.Exit(code=1) from error

    if not assessments:
        typer.echo("No test command candidates detected.")
        return

    typer.echo("Safety\tConfidence\tSource\tWorking directory\tCommand\tReason")
    for assessment in assessments:
        candidate = assessment.candidate
        safety = "safe" if assessment.safety.is_safe else "unsafe"
        command_text = " ".join(candidate.command)
        reason = candidate.reason
        if assessment.safety.reason:
            reason = f"{reason} ({assessment.safety.reason})"
        typer.echo(
            "\t".join(
                [
                    safety,
                    f"{candidate.confidence:.2f}",
                    candidate.source_type,
                    str(candidate.working_directory.resolve(strict=False)),
                    command_text,
                    reason,
                ]
            )
        )


@test_app.command("run")
def run_test_command(
    project_root: Annotated[
        Path,
        typer.Option(
            "--project-root",
            exists=True,
            file_okay=False,
            dir_okay=True,
            resolve_path=True,
            help="Project root where tests should be detected and run.",
        ),
    ],
    command: Annotated[
        str | None,
        typer.Option(
            "--command",
            help="Explicit test command to run instead of auto-detection.",
        ),
    ] = None,
    timeout_seconds: Annotated[
        int,
        typer.Option("--timeout", help="Maximum test command runtime in seconds."),
    ] = DEFAULT_TEST_TIMEOUT_SECONDS,
) -> None:
    """Run an explicit or auto-detected safe test command."""
    try:
        result = TestRunner().run(
            project_root=project_root,
            command=command,
            timeout_seconds=timeout_seconds,
        )
    except TestRunError as error:
        typer.echo(f"Error: {error}", err=True)
        if error.run_directory is not None:
            typer.echo(f"Test artifacts: {error.run_directory}", err=True)
        raise typer.Exit(code=1) from error

    typer.echo(f"Test command: {' '.join(result.selected_command)}")
    typer.echo(f"Command source: {result.command_source}")
    typer.echo(f"Status: {result.status}")
    typer.echo(f"Exit code: {result.exit_code}")
    typer.echo(f"Test artifacts: {result.run_directory}")

    if result.exit_code not in (None, 0):
        raise typer.Exit(code=result.exit_code)
    if result.timed_out or result.status == "error":
        raise typer.Exit(code=1)


@dev_app.command("run")
def run_dev_pipeline(
    input_text: Annotated[
        str,
        typer.Option("--input", help="Request for the dev pipeline to process."),
    ],
    project_root: Annotated[
        Path | None,
        typer.Option(
            "--project-root",
            exists=True,
            file_okay=False,
            dir_okay=True,
            resolve_path=True,
            help="Project root where approved patches and tests should run.",
        ),
    ] = None,
    workflow_path: Annotated[
        Path,
        typer.Option("--workflow", help="Workflow YAML file to run."),
    ] = DEFAULT_DEV_WORKFLOW_PATH,
    yes: Annotated[
        bool,
        typer.Option("--yes", help="Apply all proposed patches without prompting."),
    ] = False,
    max_cycles: Annotated[
        int,
        typer.Option("--max-cycles", help="Maximum dev cycles. Defaults to 1 in Phase 6."),
    ] = 1,
) -> None:
    """Run the Phase 6 end-to-end development pipeline."""
    resolved_project_root = Path.cwd() if project_root is None else project_root
    resolved_workflow_path = _resolve_workflow_path(workflow_path)

    try:
        pipeline = DevPipelineRunner()
        session = pipeline.prepare(
            user_request=input_text,
            project_root=resolved_project_root,
            workflow_path=resolved_workflow_path,
            max_cycles=max_cycles,
        )
    except DevPipelineError as error:
        typer.echo(f"Error: {error}", err=True)
        if error.run_directory is not None:
            typer.echo(f"Run artifacts: {error.run_directory}", err=True)
        raise typer.Exit(code=1) from error

    _echo_dev_approval_summary(session)
    approved = yes
    if not approved:
        approved = typer.confirm("Apply all proposed patches?", default=False)

    try:
        result = pipeline.finish(session, approved=approved)
    except DevPipelineError as error:
        typer.echo(f"Error: {error}", err=True)
        if error.run_directory is not None:
            typer.echo(f"Run artifacts: {error.run_directory}", err=True)
        raise typer.Exit(code=1) from error

    _echo_dev_completion(result, approved=approved)


def _exit_with_error(error: PatchReviewError) -> None:
    typer.echo(f"Error: {error}", err=True)
    raise typer.Exit(code=1) from error


def _resolve_workflow_path(workflow_path: Path) -> Path:
    if workflow_path.exists() or workflow_path.is_absolute():
        return workflow_path.resolve(strict=False)

    repository_candidate = Path(__file__).resolve().parents[2] / workflow_path
    if repository_candidate.exists():
        return repository_candidate.resolve()

    return workflow_path.resolve(strict=False)


def _echo_dev_approval_summary(session: DevRunSession) -> None:
    typer.echo("AgentForge Dev Run")
    typer.echo()
    typer.echo("Request:")
    typer.echo(session.user_request)
    typer.echo()
    typer.echo("Project root:")
    typer.echo(str(session.project_root.resolve(strict=False)))
    typer.echo()
    typer.echo("Workflow:")
    typer.echo(str(session.workflow_path))
    typer.echo()
    typer.echo(f"Cycle {session.cycle_number}")
    typer.echo()
    typer.echo("Planner:")
    typer.echo(f"- {session.planner_summary}")
    typer.echo()
    typer.echo("Selected agents:")
    if session.selected_agents:
        for agent_name in session.selected_agents:
            typer.echo(f"- {agent_name}")
    else:
        typer.echo("- None")
    typer.echo()
    typer.echo("Generated patches:")
    if session.generated_patches:
        for index, patch in enumerate(session.generated_patches, start=1):
            typer.echo(f"{index}. {patch['id']} -> {patch['target_file']}")
    else:
        typer.echo("- None")
    typer.echo()


def _echo_dev_completion(result: DevRunResult, *, approved: bool) -> None:
    if not approved:
        typer.echo()
        typer.echo("No changes were applied.")
    else:
        typer.echo()
        typer.echo("Applying patches...")
        if result.applied_patches:
            for patch in result.applied_patches:
                typer.echo(f"[ok] Applied {patch['id']}")
        else:
            typer.echo("[ok] No proposed patches to apply")

        typer.echo()
        typer.echo("Running tests...")
        if result.test_command:
            typer.echo(f"[ok] Detected command: {' '.join(result.test_command)}")
        else:
            typer.echo("[warn] No test command was selected")

        if result.test_status == "passed":
            typer.echo("[ok] Tests passed")
        else:
            typer.echo(f"[warn] Tests ended with status: {result.test_status}")

    decision = result.planner_decisions[-1] if result.planner_decisions else {}
    typer.echo()
    typer.echo("Planner decision:")
    notes = decision.get("notes", [])
    if isinstance(notes, list):
        for note in notes:
            typer.echo(f"- {note}")
    if decision.get("next_action"):
        typer.echo(f"- Next action: {decision['next_action']}")

    typer.echo()
    typer.echo("Final verdict:")
    typer.echo(result.final_verdict)
    typer.echo()
    typer.echo("Artifacts:")
    typer.echo(str(result.run_directory))


if __name__ == "__main__":
    app()
